Generate custom `winmd` from headers with improved annotations
The winmd shipped with the NuGet package has an [indecisive license][1],
as it's intended to fall under the MIT license just like other code
files, but is strictly a binary blob.  At the same time the metadata
[isn't representing the headers as conveniently and completely][2] as
we'd like in our Rust bindings, but unfortunately there is no upstream
source available to reference or contribute to, where we can tweak and
improve how the NuGet `winmd` is generated.

The metadata description introduced here tries to reproduce the original
metadata as closely as possible, while following the improvements
[that I requested upstream][2] and [maintaining the `int` type for
`DSTORAGE_DEBUG`][3].

[1]: https://github.com/microsoft/DirectStorage/issues/8#issuecomment-1875760330
[2]: https://github.com/microsoft/DirectStorage/issues/38
[3]: https://github.com/microsoft/win32metadata/issues/1822#issuecomment-1894407892

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,21 +39,40 @@ jobs:
       - name: Cargo clippy with minimal-versions
         run: cargo +stable clippy --workspace --all-targets -- -D warnings
 
-  generate-rust:
-    name: Generate Rust crate
-    runs-on: ubuntu-latest
+  generate-winmd:
+    name: Generate winmd
+    runs-on: windows-2022
     steps:
       - uses: actions/checkout@v4
       - name: Clean
-        run: rm -rf .windows/winmd/* src/Microsoft.rs
-      - name: Download winmd
+        run: Remove-Item -Recurse -Force -ErrorAction SilentlyContinue .windows/winmd/
+      - name: Configure environment
+        shell: pwsh
         run: |
-          curl -L https://www.nuget.org/api/v2/package/Microsoft.Direct3D.DirectStorage/$DIRECTSTORAGE_VERSION -o microsoft.direct3d.directstorage.$DIRECTSTORAGE_VERSION.nupkg
-          unzip microsoft.direct3d.directstorage.$DIRECTSTORAGE_VERSION.nupkg native/winmd/Microsoft.Direct3D.DirectStorage.winmd
-          mkdir -p .windows/winmd/
-          mv native/winmd/Microsoft.Direct3D.DirectStorage.winmd .windows/winmd/
-          rm native -rf
-          rm microsoft.direct3d.directstorage.$DIRECTSTORAGE_VERSION.nupkg
+          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64" >> $env:GITHUB_PATH
+          ((Resolve-Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\*\bin\Hostx64\x64")
+            | Sort-Object -Descending | Select -First 1).ToString() >> $env:GITHUB_PATH
+      - name: Generate
+        run: dotnet build .metadata
+      - name: Upload
+        uses: actions/upload-artifact@v4
+        with:
+          name: metadata
+          path: .windows/winmd
+
+  generate-rust:
+    name: Generate Rust crate
+    runs-on: ubuntu-latest
+    needs: generate-winmd
+    steps:
+      - uses: actions/checkout@v4
+      - name: Clean
+        run: rm -rf .windows/winmd/ src/Microsoft_Direct3D_DirectStorage.rs
+      - name: Download winmd
+        uses: actions/download-artifact@v4
+        with:
+          name: metadata
+          path: .windows/winmd
       - name: Generate
         run: cargo r -p api_gen
       - name: Upload crate source
@@ -62,4 +81,4 @@ jobs:
           name: crate-source
           path: src/
       - name: Diff generated Rust code
-        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p api_gen!"; git status; false)
+        run: test -z "$(git status --porcelain -- ':!.windows')" || (echo "::error::Generated files are different, please regenerate with cargo run -p api_gen!"; git status; false)
